[secrets]
MONGOBD_CONNECTION_STRING = "mongodb+srv://<username>:<password>@cluster0.mwmxpcy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
[secrets]
DEEPSEEK_API = '4197f424eefbab7d578e590b'
[secrets]
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
[secrets]
EMAIL_USER = ""
[secrets]
EMAIL_PASSWORD = ""