[secrets]
MONGOBD_CONNECTION_STRING = "mongodb+srv://zayd88903:zayd202020@cluster0.mwmxpcy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

DEEPSEEK_API = 'sk-96d964197f424eefbab7d578e590b335'

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USER = "elouaragli.zayd@etu.uae.ac.ma"
EMAIL_PASSWORD = "fsyk rqyz axog mhpz"